#!/bin/sh

BACKUP_DIR="/var/mobile/Library/HideAVControlsBackup"

AUDIO="/var/Managed Preferences/mobile/com.apple.replaykit.AudioConferenceControlCenterModule.plist"
VIDEO="/var/Managed Preferences/mobile/com.apple.replaykit.VideoConferenceControlCenterModule.plist"

AUDIO_BACKUP="$BACKUP_DIR/AudioConferenceControlCenterModule.plist"
VIDEO_BACKUP="$BACKUP_DIR/VideoConferenceControlCenterModule.plist"

AUDIO_ABSENT="$BACKUP_DIR/AudioConferenceControlCenterModule.absent"
VIDEO_ABSENT="$BACKUP_DIR/VideoConferenceControlCenterModule.absent"


mkdir -p "$BACKUP_DIR"


# Audio
if [ -f "$AUDIO_BACKUP" ] || [ -f "$AUDIO_ABSENT" ]; then
    true
else
    if [ -f "$AUDIO" ]; then
        cp "$AUDIO" "$AUDIO_BACKUP"
    else
        touch "$AUDIO_ABSENT"
    fi
fi


# Video
if [ -f "$VIDEO_BACKUP" ] || [ -f "$VIDEO_ABSENT" ]; then
    true
else
    if [ -f "$VIDEO" ]; then
        cp "$VIDEO" "$VIDEO_BACKUP"
    else
        touch "$VIDEO_ABSENT"
    fi
fi


killall -9 SpringBoard 2>/dev/null || true

exit 0